name = 'Sophist'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Sophist is a minimal theme for blogs that focuses on beautiful typography.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
# tags = ['blog', 'company']
# features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'mason-1009'
  homepage = 'https://sophist.space/'
